// ==== SINGLE SOURCE OF TRUTH FOR ALL BUFFER SIZES ====
// THIS is the ONLY place we define the master buffer size!
// Change this ONE constant to adjust ALL buffer behavior system-wide.
pub const MASTER_BUFFER_SIZE: usize = 1024 * 1024; // 1MB - THE source of truth

// All other buffer sizes derive from the master constant - NO MAGIC NUMBERS!
pub const STREAM_CHUNK_SIZE: usize = MASTER_BUFFER_SIZE; // Streaming chunk size
pub const STREAMING_THRESHOLD: usize = MASTER_BUFFER_SIZE.saturating_sub(1024); // Just under buffer limit

struct IoPerfCounters {
    read_calls: AtomicU64,
    read_ns: AtomicU64,
    actor_handle_calls: AtomicU64,
    actor_handle_ns: AtomicU64,
    response_write_calls: AtomicU64,
    response_write_ns: AtomicU64,
    ask_write_calls: AtomicU64,
    ask_write_ns: AtomicU64,
}

fn flush_each_actor_response() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    *ENABLED.get_or_init(|| {
        std::env::var("ICANACT_REMOTE_FLUSH_EACH_RESPONSE")
            .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
            .unwrap_or(false)
    })
}

/// Batched actor ask responses generated by the IO task.
///
/// Avoids per-response `write().await` overhead by writing many small frames in a few
/// `write_vectored` calls. Payloads are kept zero-copy via `bytes::Bytes`.
#[derive(Debug)]
struct ResponseBatch {
    correlation_ids: Vec<u16>,
    payloads: Vec<bytes::Bytes>,
}

impl ResponseBatch {
    fn new(capacity: usize) -> Self {
        Self {
            correlation_ids: Vec::with_capacity(capacity),
            payloads: Vec::with_capacity(capacity),
        }
    }

    fn clear(&mut self) {
        self.correlation_ids.clear();
        self.payloads.clear();
    }

    fn is_empty(&self) -> bool {
        self.payloads.is_empty()
    }

    fn push_bytes(&mut self, correlation_id: u16, payload: bytes::Bytes) {
        self.correlation_ids.push(correlation_id);
        self.payloads.push(payload);
    }
}

/// Batched direct ask responses generated by the IO task.
#[derive(Debug)]
struct DirectResponseBatch {
    correlation_ids: Vec<u16>,
    payloads: Vec<bytes::Bytes>,
}

impl DirectResponseBatch {
    fn new(capacity: usize) -> Self {
        Self {
            correlation_ids: Vec::with_capacity(capacity),
            payloads: Vec::with_capacity(capacity),
        }
    }

    fn clear(&mut self) {
        self.correlation_ids.clear();
        self.payloads.clear();
    }

    fn is_empty(&self) -> bool {
        self.payloads.is_empty()
    }

    fn push_bytes(&mut self, correlation_id: u16, payload: bytes::Bytes) {
        self.correlation_ids.push(correlation_id);
        self.payloads.push(payload);
    }
}

async fn write_remaining_chunks<S: AsyncWrite + Unpin>(
    stream: &mut S,
    chunks: &[bytes::Bytes],
    mut offset: usize,
) -> std::io::Result<usize> {
    let mut wrote = 0usize;
    for chunk in chunks {
        if offset >= chunk.len() {
            offset -= chunk.len();
            continue;
        }
        stream.write_all(&chunk[offset..]).await?;
        wrote += chunk.len() - offset;
        offset = 0;
    }
    Ok(wrote)
}

async fn write_chunks_batched<S: AsyncWrite + Unpin>(
    stream: &mut S,
    chunks: &[bytes::Bytes],
) -> std::io::Result<usize> {
    if chunks.is_empty() {
        return Ok(0);
    }

    if !stream.is_write_vectored() {
        return write_remaining_chunks(stream, chunks, 0).await;
    }

    const MAX_IOV: usize = 64;
    let mut total = 0usize;
    let mut idx = 0usize;
    let mut batch_start = 0usize;
    let mut iov: [MaybeUninit<std::io::IoSlice<'_>>; MAX_IOV] = unsafe {
        MaybeUninit::<[MaybeUninit<std::io::IoSlice<'_>>; MAX_IOV]>::uninit().assume_init()
    };

    for (i, chunk) in chunks.iter().enumerate() {
        if idx == 0 {
            batch_start = i;
        }
        iov[idx].write(std::io::IoSlice::new(chunk));
        idx += 1;

        if idx == MAX_IOV {
            let batch = &chunks[batch_start..batch_start + idx];
            let batch_total: usize = batch.iter().map(|c| c.len()).sum();
            let slices = unsafe {
                std::slice::from_raw_parts(iov.as_ptr() as *const std::io::IoSlice<'_>, idx)
            };
            let n = stream.write_vectored(slices).await?;
            total += n;
            if n < batch_total {
                total += write_remaining_chunks(stream, batch, n).await?;
            }
            idx = 0;
        }
    }

    if idx > 0 {
        let batch = &chunks[batch_start..batch_start + idx];
        let batch_total: usize = batch.iter().map(|c| c.len()).sum();
        let slices =
            unsafe { std::slice::from_raw_parts(iov.as_ptr() as *const std::io::IoSlice<'_>, idx) };
        let n = stream.write_vectored(slices).await?;
        total += n;
        if n < batch_total {
            total += write_remaining_chunks(stream, batch, n).await?;
        }
    }

    Ok(total)
}

async fn write_header_payload_all<S: AsyncWrite + Unpin>(
    stream: &mut S,
    header: &[u8],
    payload: &[u8],
) -> std::io::Result<usize> {
    let total_len = header.len() + payload.len();
    if total_len == 0 {
        return Ok(0);
    }

    if !stream.is_write_vectored() {
        if !header.is_empty() {
            stream.write_all(header).await?;
        }
        if !payload.is_empty() {
            stream.write_all(payload).await?;
        }
        return Ok(total_len);
    }

    let mut slices = [
        std::io::IoSlice::new(header),
        std::io::IoSlice::new(payload),
    ];
    let slice_count = if header.is_empty() {
        slices[0] = std::io::IoSlice::new(payload);
        1
    } else if payload.is_empty() {
        slices[0] = std::io::IoSlice::new(header);
        1
    } else {
        2
    };

    let n = stream.write_vectored(&slices[..slice_count]).await?;
    if n == total_len {
        return Ok(n);
    }

    let mut written = n;
    if written < header.len() {
        stream.write_all(&header[written..]).await?;
        written = header.len();
    }

    let payload_off = written.saturating_sub(header.len());
    if payload_off < payload.len() {
        stream.write_all(&payload[payload_off..]).await?;
    }

    Ok(total_len)
}

async fn write_response_batch<S>(
    stream: &mut S,
    bytes_written_counter: &Arc<AtomicUsize>,
    bytes_since_flush: &mut usize,
    batch: &mut ResponseBatch,
) -> Result<()>
where
    S: AsyncWrite + Unpin,
{
    if batch.is_empty() {
        return Ok(());
    }
    debug_assert_eq!(
        batch.correlation_ids.len(),
        batch.payloads.len(),
        "ResponseBatch must keep correlation_ids and payloads in sync"
    );
    if batch.payloads.len() == 1 {
        let header = crate::framing::write_ask_response_header(
            crate::MessageType::Response,
            batch.correlation_ids[0],
            batch.payloads[0].len(),
        );
        let n = write_header_payload_all(stream, &header, batch.payloads[0].as_ref())
            .await
            .map_err(GossipError::Network)?;
        bytes_written_counter.fetch_add(n, Ordering::Relaxed);
        *bytes_since_flush += n;
        batch.clear();
        return Ok(());
    }

    const HDR_LEN: usize = crate::framing::ASK_RESPONSE_FRAME_HEADER_LEN;

    // Flattened slice index: [h0, p0, h1, p1, ...]
    let total_slices = batch.payloads.len().saturating_mul(2);
    let mut cur_slice = 0usize;
    let mut cur_off = 0usize;

    // Larger iov batches reduce syscalls under heavy ActorAsk load. 256 is well below typical
    // platform limits (often 1024) while keeping stack scratch buffers modest.
    const MAX_IOV: usize = 256;
    let mut iov: [MaybeUninit<std::io::IoSlice<'_>>; MAX_IOV] = unsafe {
        MaybeUninit::<[MaybeUninit<std::io::IoSlice<'_>>; MAX_IOV]>::uninit().assume_init()
    };
    // Scratch headers for this writev attempt. We regenerate headers from (corr_id, payload_len)
    // so we don't need to store per-response headers on the heap.
    let mut scratch_headers: [MaybeUninit<[u8; HDR_LEN]>; MAX_IOV] =
        unsafe { MaybeUninit::<[MaybeUninit<[u8; HDR_LEN]>; MAX_IOV]>::uninit().assume_init() };

    while cur_slice < total_slices {
        let mut iov_len = 0usize;
        // Build up to MAX_IOV slices starting from current position.
        while iov_len < MAX_IOV && (cur_slice + iov_len) < total_slices {
            let k = cur_slice + iov_len;
            let resp_idx = k / 2;
            let is_header = (k & 1) == 0;
            let slice_bytes: &[u8] = if is_header {
                let header = crate::framing::write_ask_response_header(
                    crate::MessageType::Response,
                    batch.correlation_ids[resp_idx],
                    batch.payloads[resp_idx].len(),
                );
                // Use raw pointers so the borrow checker understands per-index disjointness.
                let hdr_slot = unsafe { scratch_headers.as_mut_ptr().add(iov_len) };
                unsafe {
                    (*hdr_slot).write(header);
                    (&*(*hdr_slot).as_ptr()).as_slice()
                }
            } else {
                batch.payloads[resp_idx].as_ref()
            };
            let slice_bytes = if iov_len == 0 && cur_off != 0 {
                &slice_bytes[cur_off..]
            } else {
                slice_bytes
            };
            if slice_bytes.is_empty() {
                // Skip empty payloads/headers (shouldn't happen for headers).
                if iov_len == 0 {
                    cur_slice += 1;
                    cur_off = 0;
                    continue;
                } else {
                    break;
                }
            }
            iov[iov_len].write(std::io::IoSlice::new(slice_bytes));
            iov_len += 1;
        }

        if iov_len == 0 {
            break;
        }

        let slices = unsafe {
            std::slice::from_raw_parts(iov.as_ptr() as *const std::io::IoSlice<'_>, iov_len)
        };

        let n = stream
            .write_vectored(slices)
            .await
            .map_err(GossipError::Network)?;
        if n == 0 {
            return Err(GossipError::Network(std::io::Error::new(
                std::io::ErrorKind::WriteZero,
                "write_vectored returned 0",
            )));
        }
        bytes_written_counter.fetch_add(n, Ordering::Relaxed);
        *bytes_since_flush += n;

        // Advance across slices by `n` bytes.
        let mut remaining = n;
        while remaining > 0 && cur_slice < total_slices {
            let resp_idx = cur_slice / 2;
            let is_header = (cur_slice & 1) == 0;
            let slice_len = if is_header {
                HDR_LEN
            } else {
                batch.payloads[resp_idx].len()
            };
            let avail = slice_len.saturating_sub(cur_off);
            if remaining < avail {
                cur_off += remaining;
                remaining = 0;
            } else {
                remaining -= avail;
                cur_slice += 1;
                cur_off = 0;
            }
        }
    }

    batch.clear();
    Ok(())
}

async fn write_direct_response_batch<S>(
    stream: &mut S,
    bytes_written_counter: &Arc<AtomicUsize>,
    bytes_since_flush: &mut usize,
    batch: &mut DirectResponseBatch,
) -> Result<()>
where
    S: AsyncWrite + Unpin,
{
    if batch.is_empty() {
        return Ok(());
    }
    debug_assert_eq!(
        batch.correlation_ids.len(),
        batch.payloads.len(),
        "DirectResponseBatch must keep correlation_ids and payloads in sync"
    );
    if batch.payloads.len() == 1 {
        let header = crate::framing::write_direct_response_header(
            batch.correlation_ids[0],
            batch.payloads[0].len(),
        );
        let n = write_header_payload_all(stream, &header, batch.payloads[0].as_ref())
            .await
            .map_err(GossipError::Network)?;
        bytes_written_counter.fetch_add(n, Ordering::Relaxed);
        *bytes_since_flush += n;
        batch.clear();
        return Ok(());
    }

    const HDR_LEN: usize = crate::framing::DIRECT_RESPONSE_FRAME_HEADER_LEN;
    let total_slices = batch.payloads.len().saturating_mul(2);
    let mut cur_slice = 0usize;
    let mut cur_off = 0usize;

    const MAX_IOV: usize = 256;
    let mut iov: [MaybeUninit<std::io::IoSlice<'_>>; MAX_IOV] = unsafe {
        MaybeUninit::<[MaybeUninit<std::io::IoSlice<'_>>; MAX_IOV]>::uninit().assume_init()
    };
    let mut scratch_headers: [MaybeUninit<[u8; HDR_LEN]>; MAX_IOV] =
        unsafe { MaybeUninit::<[MaybeUninit<[u8; HDR_LEN]>; MAX_IOV]>::uninit().assume_init() };

    while cur_slice < total_slices {
        let mut iov_len = 0usize;
        while iov_len < MAX_IOV && (cur_slice + iov_len) < total_slices {
            let k = cur_slice + iov_len;
            let resp_idx = k / 2;
            let is_header = (k & 1) == 0;
            let slice_bytes: &[u8] = if is_header {
                let header = crate::framing::write_direct_response_header(
                    batch.correlation_ids[resp_idx],
                    batch.payloads[resp_idx].len(),
                );
                let hdr_slot = unsafe { scratch_headers.as_mut_ptr().add(iov_len) };
                unsafe {
                    (*hdr_slot).write(header);
                    (&*(*hdr_slot).as_ptr()).as_slice()
                }
            } else {
                batch.payloads[resp_idx].as_ref()
            };
            let slice_bytes = if iov_len == 0 && cur_off != 0 {
                &slice_bytes[cur_off..]
            } else {
                slice_bytes
            };
            if slice_bytes.is_empty() {
                if iov_len == 0 {
                    cur_slice += 1;
                    cur_off = 0;
                    continue;
                } else {
                    break;
                }
            }
            iov[iov_len].write(std::io::IoSlice::new(slice_bytes));
            iov_len += 1;
        }

        if iov_len == 0 {
            break;
        }

        let slices = unsafe {
            std::slice::from_raw_parts(iov.as_ptr() as *const std::io::IoSlice<'_>, iov_len)
        };

        let n = stream
            .write_vectored(slices)
            .await
            .map_err(GossipError::Network)?;
        bytes_written_counter.fetch_add(n, Ordering::Relaxed);
        *bytes_since_flush += n;

        let mut remaining = n;
        while remaining > 0 {
            let resp_idx = cur_slice / 2;
            let is_header = (cur_slice & 1) == 0;
            let full_len = if is_header {
                HDR_LEN
            } else {
                batch.payloads[resp_idx].len()
            };
            let rem_in_slice = full_len - cur_off;
            if remaining < rem_in_slice {
                cur_off += remaining;
                remaining = 0;
            } else {
                remaining -= rem_in_slice;
                cur_slice += 1;
                cur_off = 0;
            }
        }
    }

    batch.clear();
    Ok(())
}

impl IoPerfCounters {
    fn global() -> &'static IoPerfCounters {
        static PERF: OnceLock<IoPerfCounters> = OnceLock::new();
        PERF.get_or_init(|| IoPerfCounters {
            read_calls: AtomicU64::new(0),
            read_ns: AtomicU64::new(0),
            actor_handle_calls: AtomicU64::new(0),
            actor_handle_ns: AtomicU64::new(0),
            response_write_calls: AtomicU64::new(0),
            response_write_ns: AtomicU64::new(0),
            ask_write_calls: AtomicU64::new(0),
            ask_write_ns: AtomicU64::new(0),
        })
    }

    fn enabled() -> bool {
        static ENABLED: OnceLock<bool> = OnceLock::new();
        *ENABLED.get_or_init(|| {
            std::env::var("ICANACT_REMOTE_IO_PERF")
                .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
                .unwrap_or(false)
        })
    }

    fn interval() -> Duration {
        static INTERVAL: OnceLock<Duration> = OnceLock::new();
        *INTERVAL.get_or_init(|| {
            let ms = std::env::var("ICANACT_REMOTE_IO_PERF_MS")
                .ok()
                .and_then(|v| v.parse::<u64>().ok())
                .filter(|v| *v > 0)
                .unwrap_or(1000);
            Duration::from_millis(ms)
        })
    }

    fn snapshot_and_reset(&self) -> (u64, u64, u64, u64, u64, u64, u64, u64) {
        (
            self.read_calls.swap(0, Ordering::Relaxed),
            self.read_ns.swap(0, Ordering::Relaxed),
            self.actor_handle_calls.swap(0, Ordering::Relaxed),
            self.actor_handle_ns.swap(0, Ordering::Relaxed),
            self.response_write_calls.swap(0, Ordering::Relaxed),
            self.response_write_ns.swap(0, Ordering::Relaxed),
            self.ask_write_calls.swap(0, Ordering::Relaxed),
            self.ask_write_ns.swap(0, Ordering::Relaxed),
        )
    }
}

/// Tracks spawned tasks for a connection.
///
/// ## Lifecycle Rules (H-004)
/// - `set_writer`/`set_reader` should only be called when establishing NEW connections
/// - Do NOT call set_* during reconnect while messages are in flight
/// - Call `abort_all()` only when the connection is being permanently torn down
/// - For reconnection: let old tasks complete naturally, then set new handles
#[derive(Debug, Default)]
pub struct TaskTracker {
    writer: ArcSwapOption<AbortHandle>,
    reader: ArcSwapOption<AbortHandle>,
}

impl TaskTracker {
    /// Create a new empty TaskTracker.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set writer handle. Only call for NEW connections, not reconnects.
    pub fn set_writer(&self, handle: AbortHandle) {
        if let Some(old) = self.writer.swap(Some(Arc::new(handle))) {
            old.abort();
        }
    }

    /// Set reader handle. Only call for NEW connections, not reconnects.
    pub fn set_reader(&self, handle: AbortHandle) {
        if let Some(old) = self.reader.swap(Some(Arc::new(handle))) {
            old.abort();
        }
    }

    /// Abort all tracked tasks.
    pub fn abort_all(&self) {
        if let Some(h) = self.writer.swap(None) {
            h.abort();
        }
        if let Some(h) = self.reader.swap(None) {
            h.abort();
        }
    }
}

impl Drop for TaskTracker {
    fn drop(&mut self) {
        self.abort_all();
    }
}

/// Buffer configuration that encapsulates all buffer-related settings
///
/// This struct ensures that the streaming threshold is always derived from the actual buffer size,
/// preventing the disconnection between buffer size and streaming decisions that causes message loss.
#[derive(Debug, Clone)]
pub struct BufferConfig {
    tcp_buffer_size: usize, // Size in bytes for TCP buffers
    ask_window: usize,
    write_queue_capacity: usize,
}

struct WriteQueue {
    queue: crossbeam_queue::ArrayQueue<WriteCommand>,
    data_notify: Notify,
    space_notify: Notify,
    /// Set true when the owning IO writer task has exited (teardown). A blocked
    /// `push()` observes this after being woken via the space notifier and
    /// returns `ConnectionClosed` instead of re-parking forever. Hot path never
    /// reads this flag.
    closed: AtomicBool,
    /// Peer address used to construct the `ConnectionClosed` error on teardown.
    addr: SocketAddr,
}

impl WriteQueue {
    fn new(capacity: usize, addr: SocketAddr) -> Arc<Self> {
        Arc::new(Self {
            queue: crossbeam_queue::ArrayQueue::new(capacity.max(128)),
            data_notify: Notify::new(),
            space_notify: Notify::new(),
            closed: AtomicBool::new(false),
            addr,
        })
    }

    fn try_push(&self, command: WriteCommand) -> std::result::Result<(), WriteCommand> {
        self.queue.push(command)
    }

    #[inline]
    fn notify_data_if_empty_to_non_empty(&self) {
        // Notify writer only on empty->non-empty transition to avoid wake storms
        // under high-throughput tell workloads.
        if self.queue.len() == 1 {
            self.data_notify.notify_one();
        }
    }

    /// Mark the queue closed and wake every task parked in `push()` so it can
    /// observe the close and return an error instead of hanging forever.
    /// Teardown-only; never called on the message fast path.
    fn mark_closed_and_wake(&self) {
        self.closed.store(true, Ordering::Release);
        self.space_notify.notify_waiters();
    }

    async fn push(&self, mut command: WriteCommand) -> Result<()> {
        // Fast reject if the writer already tore down before we attempt to park.
        if self.closed.load(Ordering::Acquire) {
            return Err(GossipError::ConnectionClosed(self.addr));
        }
        loop {
            match self.queue.push(command) {
                Ok(()) => {
                    self.notify_data_if_empty_to_non_empty();
                    return Ok(());
                }
                Err(cmd) => {
                    command = cmd;
                    // Register on the space notifier *before* re-checking
                    // `closed`. `mark_closed_and_wake` signals via
                    // `notify_waiters()`, which stores no permit for an
                    // unregistered waiter, so a teardown landing between the
                    // failed push and the await would otherwise be lost and
                    // park this sender forever. `enable()` arms the waiter so
                    // any close after this point is delivered to the await
                    // below, and the close-before-enable case is caught by the
                    // load that follows. Backpressure-branch only; never on the
                    // `try_push` fast path.
                    let notified = self.space_notify.notified();
                    tokio::pin!(notified);
                    notified.as_mut().enable();
                    if self.closed.load(Ordering::Acquire) {
                        return Err(GossipError::ConnectionClosed(self.addr));
                    }
                    notified.await;
                    if self.closed.load(Ordering::Acquire) {
                        return Err(GossipError::ConnectionClosed(self.addr));
                    }
                }
            }
        }
    }

    fn pop(&self) -> Option<WriteCommand> {
        self.queue.pop()
    }

    fn notify_space(&self) {
        self.space_notify.notify_one();
    }
}

struct StreamingQueue {
    queue: crossbeam_queue::ArrayQueue<StreamingCommand>,
    data_notify: Notify,
    space_notify: Notify,
    /// Set true when the owning IO writer task has exited (teardown). See
    /// `WriteQueue::closed`. Hot path never reads this flag.
    closed: AtomicBool,
    /// Coordinates non-blocking enqueues with teardown. The high bit is the
    /// closed flag; lower bits count enqueues that have started but not yet
    /// committed their result. An enqueue overlapping teardown must return
    /// `Closed`, even if it managed to append a command before the writer quit.
    try_push_state: AtomicUsize,
    /// Peer address used to construct the `ConnectionClosed` error on teardown.
    addr: SocketAddr,
}

const STREAMING_QUEUE_CLOSED: usize = 1usize << (usize::BITS - 1);
const STREAMING_QUEUE_PUSHERS: usize = !STREAMING_QUEUE_CLOSED;

#[derive(Debug)]
enum StreamingTryPushError {
    Closed(SocketAddr),
    Full(StreamingCommand),
}

impl StreamingQueue {
    fn new(capacity: usize, addr: SocketAddr) -> Arc<Self> {
        Arc::new(Self {
            queue: crossbeam_queue::ArrayQueue::new(capacity.max(64)),
            data_notify: Notify::new(),
            space_notify: Notify::new(),
            closed: AtomicBool::new(false),
            try_push_state: AtomicUsize::new(0),
            addr,
        })
    }

    fn try_push(
        &self,
        command: StreamingCommand,
    ) -> std::result::Result<(), StreamingTryPushError> {
        loop {
            let state = self.try_push_state.load(Ordering::Acquire);
            if state & STREAMING_QUEUE_CLOSED != 0 {
                return Err(StreamingTryPushError::Closed(self.addr));
            }
            debug_assert!(state & STREAMING_QUEUE_PUSHERS != STREAMING_QUEUE_PUSHERS);
            if self
                .try_push_state
                .compare_exchange_weak(state, state + 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
            {
                break;
            }
        }

        let result = match self.queue.push(command) {
            Ok(()) => {
                self.notify_data_if_empty_to_non_empty();
                Ok(())
            }
            Err(cmd) => Err(StreamingTryPushError::Full(cmd)),
        };
        let state = self.try_push_state.fetch_sub(1, Ordering::AcqRel);
        if state & STREAMING_QUEUE_CLOSED != 0 {
            return Err(StreamingTryPushError::Closed(self.addr));
        }
        result
    }

    #[inline]
    fn notify_data_if_empty_to_non_empty(&self) {
        if self.queue.len() == 1 {
            self.data_notify.notify_one();
        }
    }

    /// Mark the queue closed and wake every task parked in `push()`. Teardown-only.
    fn mark_closed_and_wake(&self) {
        self.try_push_state
            .fetch_or(STREAMING_QUEUE_CLOSED, Ordering::AcqRel);
        self.closed.store(true, Ordering::Release);
        self.space_notify.notify_waiters();
    }

    async fn push(&self, mut command: StreamingCommand) -> Result<()> {
        if self.closed.load(Ordering::Acquire) {
            return Err(GossipError::ConnectionClosed(self.addr));
        }
        loop {
            match self.queue.push(command) {
                Ok(()) => {
                    self.notify_data_if_empty_to_non_empty();
                    return Ok(());
                }
                Err(cmd) => {
                    command = cmd;
                    // See WriteQueue::push: register before re-checking `closed`
                    // so a teardown landing in the gap is not lost. Backpressure
                    // branch only; never on the fast path.
                    let notified = self.space_notify.notified();
                    tokio::pin!(notified);
                    notified.as_mut().enable();
                    if self.closed.load(Ordering::Acquire) {
                        return Err(GossipError::ConnectionClosed(self.addr));
                    }
                    notified.await;
                    if self.closed.load(Ordering::Acquire) {
                        return Err(GossipError::ConnectionClosed(self.addr));
                    }
                }
            }
        }
    }

    fn pop(&self) -> Option<StreamingCommand> {
        self.queue.pop()
    }

    fn notify_space(&self) {
        self.space_notify.notify_one();
    }
}

#[cfg(any(test, feature = "test-helpers", debug_assertions))]
pub(crate) fn process_mock_request(request: &str) -> Vec<u8> {
    if let Some(payload) = request.strip_prefix("ECHO:") {
        return format!("ECHOED:{}", payload).into_bytes();
    }
    if let Some(payload) = request.strip_prefix("REVERSE:") {
        let reversed: String = payload.chars().rev().collect();
        return format!("REVERSED:{}", reversed).into_bytes();
    }
    if let Some(payload) = request.strip_prefix("COUNT:") {
        return format!("COUNTED:{} chars", payload.chars().count()).into_bytes();
    }
    if let Some(payload) = request.strip_prefix("HASH:") {
        let mut hasher = Sha256::new();
        hasher.update(payload.as_bytes());
        let digest = hasher.finalize();
        return format!("HASHED:{}", hex::encode(digest)).into_bytes();
    }

    format!("RECEIVED:{} bytes, content: '{}'", request.len(), request).into_bytes()
}

#[cfg(any(test, feature = "test-helpers", debug_assertions))]
pub(crate) fn process_mock_request_payload(payload: &[u8]) -> Vec<u8> {
    if payload.len() == 4 {
        let value = u32::from_be_bytes([payload[0], payload[1], payload[2], payload[3]]);
        return (value + 1).to_be_bytes().to_vec();
    }

    let request_str = String::from_utf8_lossy(payload);
    process_mock_request(&request_str)
}

impl BufferConfig {
    /// Create a new BufferConfig with validation
    ///
    /// # Arguments
    /// * `tcp_buffer_size` - The size of TCP buffers in bytes
    ///
    /// # Errors
    /// Returns an error if the buffer size is less than 256KB for safety
    pub fn new(tcp_buffer_size: usize) -> Result<Self> {
        // Enforce minimum size of 256KB for safety
        if tcp_buffer_size < 256 * 1024 {
            return Err(GossipError::InvalidConfig(format!(
                "TCP buffer must be at least 256KB, got {}KB",
                tcp_buffer_size / 1024
            )));
        }
        Ok(Self {
            tcp_buffer_size,
            ask_window: crate::config::DEFAULT_ASK_WINDOW,
            write_queue_capacity: crate::config::DEFAULT_ASK_WINDOW.saturating_mul(8),
        })
    }

    /// Target in-flight ask window per connection.
    pub fn ask_window(&self) -> usize {
        self.ask_window
    }

    /// Override the default ask inflight limit.
    pub fn with_ask_window(mut self, limit: usize) -> Self {
        self.ask_window = limit;
        let min_capacity = limit.saturating_mul(4).max(128);
        if self.write_queue_capacity < min_capacity {
            self.write_queue_capacity = min_capacity;
        }
        self
    }

    /// Override write queue capacity (number of queued payloads before backpressure).
    pub fn with_write_queue_capacity(mut self, capacity: usize) -> Self {
        self.write_queue_capacity = capacity.max(128);
        self
    }

    /// Capacity of the write queue used by the lock-free writer task.
    pub fn write_queue_capacity(&self) -> usize {
        self.write_queue_capacity
    }

    /// Calculate the streaming threshold based on buffer size
    ///
    /// The streaming threshold is always derived from the buffer size,
    /// leaving 1KB headroom for headers and serialization overhead.
    pub fn streaming_threshold(&self) -> usize {
        // Always derive from buffer size
        // Leave 1KB headroom for headers/overhead
        self.tcp_buffer_size.saturating_sub(1024)
    }

    /// Get the TCP buffer size for BufWriter and io_uring
    ///
    /// This ensures TCP buffers match the configured size, preventing bottlenecks.
    pub fn tcp_buffer_size(&self) -> usize {
        self.tcp_buffer_size
    }

    /// Create BufferConfig using the master buffer size (recommended)
    pub fn from_master() -> Self {
        Self {
            tcp_buffer_size: MASTER_BUFFER_SIZE,
            ask_window: crate::config::DEFAULT_ASK_WINDOW,
            write_queue_capacity: crate::config::DEFAULT_ASK_WINDOW.saturating_mul(8),
        }
    }
}

impl Default for BufferConfig {
    fn default() -> Self {
        // Use master constant instead of magic number!
        Self {
            tcp_buffer_size: MASTER_BUFFER_SIZE,
            ask_window: crate::config::DEFAULT_ASK_WINDOW,
            write_queue_capacity: crate::config::DEFAULT_ASK_WINDOW.saturating_mul(8),
        }
    }
}
