// ==== SINGLE SOURCE OF TRUTH FOR ALL BUFFER SIZES ====
// THIS is the ONLY place we define the master buffer size!
// Change this ONE constant to adjust ALL buffer behavior system-wide.
pub const MASTER_BUFFER_SIZE: usize = 1024 * 1024; // 1MB - THE source of truth

// All other buffer sizes derive from the master constant - NO MAGIC NUMBERS!
pub const STREAM_CHUNK_SIZE: usize = MASTER_BUFFER_SIZE; // Streaming chunk size
pub const STREAMING_THRESHOLD: usize = MASTER_BUFFER_SIZE.saturating_sub(1024); // Just under buffer limit

// R-I (P1): the per-turn response batch drain loops in `stream_writer.rs`
// (`ResponseBatch`) were bounded only by FRAME COUNT
// (`READ_BATCH_LIMIT` = 2048, `ASK_READ_BATCH_LIMIT` = 8192), not by bytes.
// Each buffered payload can be up to `STREAMING_THRESHOLD` (~1 MiB) before it
// would instead take the streaming path, so a peer that packs its ask window
// (`DEFAULT_ASK_WINDOW`, sender-side politeness only — never enforced by the
// receiver) with max-size response frames could force up to
// `ASK_READ_BATCH_LIMIT * STREAMING_THRESHOLD` (~8 GiB) of live `Bytes` to
// accumulate in one turn before the frame-count cap ever fired. This is a
// memory-blowup DoS vector and it also inflates RTT, since nothing flushes
// while still accumulating.
//
// `RESPONSE_BATCH_BYTE_CAP` is the connection's retained-inline-response
// budget: pending ordinary write bytes plus the in-progress response batch.
// Parking a batch into `PendingOrdinaryWrite` must not drop the charge, and
// ask dispatch is NACKed (`AskNackReason::Backpressure`) once the sum reaches
// this cap — including while an ordinary frame already owns the wire. Sized at
// 8x `STREAMING_THRESHOLD` (~8 MiB): generous enough to keep the common case
// (small ask/response payloads) batching exactly as before, while capping the
// worst case (all-maximum-size payloads) at a small, fixed multiple of a
// single streaming chunk instead of thousands of them.
pub const RESPONSE_BATCH_BYTE_CAP: usize = STREAMING_THRESHOLD.saturating_mul(8);

/// Bound immediate streaming responses admitted by one connection's read
/// pipeline. Each queued command retains its `Bytes` backing allocation until
/// the frame is fully written, so both command count and retained wire bytes
/// are capped independently of the peer's request burst.
pub const STREAMING_RESPONSE_QUEUE_COMMAND_CAP: usize = 256;
pub const STREAMING_RESPONSE_QUEUE_BYTE_CAP: usize = RESPONSE_BATCH_BYTE_CAP;

struct IoPerfCounters {
    read_calls: AtomicU64,
    read_ns: AtomicU64,
    actor_handle_calls: AtomicU64,
    actor_handle_ns: AtomicU64,
    response_write_calls: AtomicU64,
    response_write_ns: AtomicU64,
    ask_write_calls: AtomicU64,
    ask_write_ns: AtomicU64,
}

/// Compact an inline reply onto its visible slice so the retained-byte budget
/// cannot be defeated by `Bytes::from_owner` / sliced views of a much larger
/// allocation. Same ownership boundary as streaming-response normalization.
fn compact_inline_reply_bytes(payload: bytes::Bytes) -> bytes::Bytes {
    bytes::Bytes::copy_from_slice(payload.as_ref())
}

/// Batched actor ask responses generated by the IO task.
///
/// Avoids per-response `write().await` overhead by writing many small frames in a few
/// `write_vectored` calls. Inline payloads are compacted onto their visible slice at
/// `push_bytes` so sliced `Bytes` owners cannot defeat the retained-byte budget.
#[derive(Debug)]
struct ResponseBatch {
    correlation_ids: Vec<u32>,
    payloads: Vec<bytes::Bytes>,
    /// Running sum of `payloads` lengths, kept in lock-step with
    /// push/clear so the drain loop can enforce `RESPONSE_BATCH_BYTE_CAP`
    /// without re-summing the batch on every check (R-I).
    total_bytes: usize,
}

impl ResponseBatch {
    fn new(capacity: usize) -> Self {
        Self {
            correlation_ids: Vec::with_capacity(capacity),
            payloads: Vec::with_capacity(capacity),
            total_bytes: 0,
        }
    }

    fn clear(&mut self) {
        self.correlation_ids.clear();
        self.payloads.clear();
        self.total_bytes = 0;
    }

    fn is_empty(&self) -> bool {
        self.payloads.is_empty()
    }

    fn push_bytes(&mut self, correlation_id: u32, payload: bytes::Bytes) {
        let payload = compact_inline_reply_bytes(payload);
        self.total_bytes += payload.len();
        self.correlation_ids.push(correlation_id);
        self.payloads.push(payload);
    }

    /// Bytes accumulated in this batch since the last `clear()`. Used by the
    /// drain loop to enforce `RESPONSE_BATCH_BYTE_CAP` (R-I).
    fn total_bytes(&self) -> usize {
        self.total_bytes
    }

    /// Drain this batch into header/payload wire chunks for a one-poll write.
    fn take_wire_chunks(&mut self) -> Result<Vec<bytes::Bytes>> {
        debug_assert_eq!(
            self.correlation_ids.len(),
            self.payloads.len(),
            "ResponseBatch must keep correlation_ids and payloads in sync"
        );
        let mut chunks = Vec::with_capacity(self.payloads.len().saturating_mul(2));
        for (correlation_id, payload) in self.correlation_ids.drain(..).zip(self.payloads.drain(..))
        {
            let header = crate::framing::try_write_ask_response_header(
                crate::MessageType::Response,
                correlation_id,
                payload.len(),
            )?;
            chunks.push(bytes::Bytes::copy_from_slice(header.as_slice()));
            chunks.push(payload);
        }
        self.total_bytes = 0;
        Ok(chunks)
    }
}

/// Batched direct ask responses generated by the IO task.
impl IoPerfCounters {
    fn global() -> &'static IoPerfCounters {
        static PERF: OnceLock<IoPerfCounters> = OnceLock::new();
        PERF.get_or_init(|| IoPerfCounters {
            read_calls: AtomicU64::new(0),
            read_ns: AtomicU64::new(0),
            actor_handle_calls: AtomicU64::new(0),
            actor_handle_ns: AtomicU64::new(0),
            response_write_calls: AtomicU64::new(0),
            response_write_ns: AtomicU64::new(0),
            ask_write_calls: AtomicU64::new(0),
            ask_write_ns: AtomicU64::new(0),
        })
    }

    fn enabled() -> bool {
        static ENABLED: OnceLock<bool> = OnceLock::new();
        *ENABLED.get_or_init(|| {
            std::env::var("ICANACT_REMOTE_IO_PERF")
                .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
                .unwrap_or(false)
        })
    }

    fn interval() -> Duration {
        static INTERVAL: OnceLock<Duration> = OnceLock::new();
        *INTERVAL.get_or_init(|| {
            let ms = std::env::var("ICANACT_REMOTE_IO_PERF_MS")
                .ok()
                .and_then(|v| v.parse::<u64>().ok())
                .filter(|v| *v > 0)
                .unwrap_or(1000);
            Duration::from_millis(ms)
        })
    }

    fn snapshot_and_reset(&self) -> (u64, u64, u64, u64, u64, u64, u64, u64) {
        (
            self.read_calls.swap(0, Ordering::Relaxed),
            self.read_ns.swap(0, Ordering::Relaxed),
            self.actor_handle_calls.swap(0, Ordering::Relaxed),
            self.actor_handle_ns.swap(0, Ordering::Relaxed),
            self.response_write_calls.swap(0, Ordering::Relaxed),
            self.response_write_ns.swap(0, Ordering::Relaxed),
            self.ask_write_calls.swap(0, Ordering::Relaxed),
            self.ask_write_ns.swap(0, Ordering::Relaxed),
        )
    }
}

/// Tracks spawned tasks for a connection.
///
/// ## Lifecycle Rules (H-004)
/// - `set_writer`/`set_reader` should only be called when establishing NEW connections
/// - Do NOT call set_* during reconnect while messages are in flight
/// - Call `abort_all()` only when the connection is being permanently torn down
/// - For reconnection: let old tasks complete naturally, then set new handles
#[derive(Debug, Default)]
pub struct TaskTracker {
    writer: ArcSwapOption<AbortHandle>,
    reader: ArcSwapOption<AbortHandle>,
}

impl TaskTracker {
    /// Create a new empty TaskTracker.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set writer handle. Only call for NEW connections, not reconnects.
    pub fn set_writer(&self, handle: AbortHandle) {
        if let Some(old) = self.writer.swap(Some(Arc::new(handle))) {
            old.abort();
        }
    }

    /// Set reader handle. Only call for NEW connections, not reconnects.
    pub fn set_reader(&self, handle: AbortHandle) {
        if let Some(old) = self.reader.swap(Some(Arc::new(handle))) {
            old.abort();
        }
    }

    /// Abort all tracked tasks.
    pub fn abort_all(&self) {
        if let Some(h) = self.writer.swap(None) {
            h.abort();
        }
        if let Some(h) = self.reader.swap(None) {
            h.abort();
        }
    }
}

impl Drop for TaskTracker {
    fn drop(&mut self) {
        self.abort_all();
    }
}

/// Buffer configuration that encapsulates all buffer-related settings
///
/// This struct ensures that the streaming threshold is always derived from the actual buffer size,
/// preventing the disconnection between buffer size and streaming decisions that causes message loss.
#[derive(Debug, Clone)]
pub struct BufferConfig {
    tcp_buffer_size: usize, // Size in bytes for TCP buffers
    ask_window: usize,
    write_queue_capacity: usize,
}

/// Test-only instrumentation for the writer queues.
///
/// The hook fires between a successful queue push and the notify decision so
/// tests can force a deterministic interleaving of concurrent producers inside
/// that window. Production builds compile none of this; test builds pay one
/// atomic load on the notify path while no hook is installed.
///
/// PR #183 review, round 8: this instrumentation is process-global, but
/// `cargo test` runs many unrelated tests concurrently, and *every*
/// `WriteQueue`/`StreamingQueue` in the process (not just the one under
/// test) calls `fire()` on every push. Two problems follow, and both are
/// fixed here rather than by adding more manual serialization at each call
/// site:
///
/// 1. **Cross-firing.** A hook installed for one connection's queue used to
///    run for *any* connection's push, so an unrelated concurrently-running
///    test's ordinary write traffic -- which has no reason to know this
///    hook exists -- could invoke it. `fire`/`install` now carry the
///    `SocketAddr` of the queue that pushed; a hook only runs for the exact
///    address it was installed against. Every test in this crate already
///    constructs its `LockFreeStreamHandle`/`WriteQueue`/`StreamingQueue`
///    with a distinct address (a unique port per test), so this alone
///    eliminates cross-test firing between any two tests that use
///    different addresses.
/// 2. **Clobbering.** The slot holds exactly one installed hook; two
///    hook-installing tests running concurrently would silently overwrite
///    each other's entry, and an `uninstall()` from one would erase the
///    other's hook mid-test. `lock()` exhaustively serializes the
///    install-through-uninstall span of every test that uses this hook
///    (whether or not their addresses differ), so only one such span is
///    ever open at a time process-wide. Every caller of `install`/
///    `uninstall` in this crate must hold this guard for that entire span.
#[cfg(test)]
mod queue_notify_hook {
    use std::net::SocketAddr;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::{Arc, Mutex, MutexGuard, OnceLock};

    pub(crate) type Hook = Arc<dyn Fn() + Send + Sync>;

    struct Installed {
        addr: SocketAddr,
        hook: Hook,
    }

    /// Fast check so the push path is a single load when no hook is installed.
    static ACTIVE: AtomicBool = AtomicBool::new(false);

    fn slot() -> &'static Mutex<Option<Installed>> {
        static SLOT: OnceLock<Mutex<Option<Installed>>> = OnceLock::new();
        SLOT.get_or_init(|| Mutex::new(None))
    }

    /// Serializes the install-through-uninstall span of every test that
    /// installs a hook. See the module doc comment's "Clobbering" note --
    /// without this, two hook-installing tests running concurrently could
    /// overwrite or erase each other's entry in `slot()` regardless of
    /// using different addresses, since there is only one slot.
    pub(crate) fn lock() -> MutexGuard<'static, ()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
    }

    /// Fired from the queue notify helpers between push and notify decision.
    /// `addr` is the pushing queue's own address; the installed hook only
    /// runs if it was installed scoped to this exact address (see the
    /// module doc comment's "Cross-firing" note).
    #[inline]
    pub(crate) fn fire(addr: SocketAddr) {
        if !ACTIVE.load(Ordering::Acquire) {
            return;
        }
        let hook = {
            let guard = slot().lock().expect("queue notify hook lock poisoned");
            guard
                .as_ref()
                .filter(|installed| installed.addr == addr)
                .map(|installed| installed.hook.clone())
        };
        if let Some(hook) = hook {
            hook();
        }
    }

    /// Caller must hold `lock()` for the entire span from this call through
    /// the matching `uninstall()`.
    pub(crate) fn install(addr: SocketAddr, hook: Hook) {
        *slot().lock().expect("queue notify hook lock poisoned") = Some(Installed { addr, hook });
        ACTIVE.store(true, Ordering::Release);
    }

    /// See `install`'s note on holding `lock()`.
    pub(crate) fn uninstall() {
        ACTIVE.store(false, Ordering::Release);
        *slot().lock().expect("queue notify hook lock poisoned") = None;
    }
}

struct WriteEnqueueGuard<'a>(&'a WriteQueue);

impl Drop for WriteEnqueueGuard<'_> {
    fn drop(&mut self) {
        self.0.try_push_state.fetch_sub(1, Ordering::AcqRel);
    }
}

#[derive(Debug)]
enum WriteTryPushError {
    #[allow(dead_code)]
    Closed(WriteCommand),
    /// Published into the queue, then observed close. The command is owned by
    /// the queue and will be reclaimed; the caller must not retry it.
    ClosedDropped,
    Full(WriteCommand),
}

struct WriteQueue {
    queue: crossbeam_queue::ArrayQueue<WriteCommand>,
    data_notify: Notify,
    space_notify: Notify,
    /// True when a producer has published data the consumer has not yet
    /// prepared to park on. Producers only fire `data_notify` on the
    /// false -> true transition (wake coalescing); the consumer clears the
    /// flag in `prepare_park()` immediately before parking.
    data_pending: AtomicBool,
    /// Set true when the owning IO writer task has exited (teardown). A blocked
    /// `push()` observes this after being woken via the space notifier and
    /// returns `ConnectionClosed` instead of re-parking forever. Hot path never
    /// reads this flag.
    closed: AtomicBool,
    /// Coordinates non-blocking enqueues with teardown. High bit is closed;
    /// lower bits count in-flight try_push callers. See `StreamingQueue`.
    try_push_state: AtomicUsize,
    /// Peer address used to construct the `ConnectionClosed` error on teardown.
    addr: SocketAddr,
}

impl WriteQueue {
    fn new(capacity: usize, addr: SocketAddr) -> Arc<Self> {
        Arc::new(Self {
            queue: crossbeam_queue::ArrayQueue::new(capacity.max(128)),
            data_notify: Notify::new(),
            space_notify: Notify::new(),
            data_pending: AtomicBool::new(false),
            closed: AtomicBool::new(false),
            try_push_state: AtomicUsize::new(0),
            addr,
        })
    }

    fn enqueue_guard(&self) -> Option<WriteEnqueueGuard<'_>> {
        loop {
            let state = self.try_push_state.load(Ordering::Acquire);
            if state & STREAMING_QUEUE_CLOSED != 0 {
                return None;
            }
            debug_assert!(state & STREAMING_QUEUE_PUSHERS != STREAMING_QUEUE_PUSHERS);
            if self
                .try_push_state
                .compare_exchange_weak(state, state + 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
            {
                return Some(WriteEnqueueGuard(self));
            }
        }
    }

    fn try_push(&self, command: WriteCommand) -> std::result::Result<(), WriteTryPushError> {
        let Some(_guard) = self.enqueue_guard() else {
            return Err(WriteTryPushError::Closed(command));
        };
        let result = match self.queue.push(command) {
            Ok(()) => Ok(()),
            Err(cmd) => Err(WriteTryPushError::Full(cmd)),
        };
        if self.try_push_state.load(Ordering::Acquire) & STREAMING_QUEUE_CLOSED != 0 {
            return Err(WriteTryPushError::ClosedDropped);
        }
        result
    }

    /// Publish a writer wakeup after a successful push, coalescing wakeups so
    /// high-throughput tell workloads do not wake-storm the writer.
    ///
    /// Only the producer that transitions `data_pending` false -> true fires
    /// the notify; `Notify::notify_one` stores a permit even when the writer
    /// is not currently parked, so the wakeup is never lost. This replaces a
    /// racy `len() == 1` empty->non-empty check: push and len() are separate
    /// operations, so two producers pushing concurrently into an empty queue
    /// could both observe len == 2 and neither would notify, leaving the
    /// writer parked forever with frames queued.
    #[inline]
    fn notify_data(&self) {
        #[cfg(test)]
        queue_notify_hook::fire(self.addr);
        if !self.data_pending.swap(true, Ordering::AcqRel) {
            self.data_notify.notify_one();
        }
    }

    /// Wake a writer parked on `data_notify` so it can re-check external
    /// state (e.g. `shutdown_signal`). `data_notify` is consumer-only —
    /// producers wake on `space_notify` — so this permit is never stolen by a
    /// producer. Used by graceful shutdown, not the message fast path.
    fn wake_consumer(&self) {
        self.data_notify.notify_one();
    }

    /// Consumer-side pre-park drain: clear `data_pending`, then re-check the
    /// queue. Must be called by the writer task immediately before parking on
    /// `data_notify`:
    /// - a push landing *after* the clear swaps false -> true and stores a
    ///   wakeup permit, so the park completes immediately;
    /// - a push landing *before* the clear is caught by the re-check pop.
    ///
    /// Returns a popped command the caller must process instead of parking;
    /// the flag is re-armed in that case so producers keep coalescing while
    /// the consumer is known-active.
    fn prepare_park(&self) -> Option<WriteCommand> {
        self.data_pending.store(false, Ordering::Release);
        let command = self.pop();
        if command.is_some() {
            self.data_pending.store(true, Ordering::Release);
        }
        command
    }

    /// Mark the queue closed and wake every task parked in `push()` so it can
    /// observe the close and return an error instead of hanging forever.
    /// Teardown-only; never called on the message fast path.
    fn mark_closed_and_wake(&self) {
        self.try_push_state
            .fetch_or(STREAMING_QUEUE_CLOSED, Ordering::AcqRel);
        self.closed.store(true, Ordering::Release);
        self.space_notify.notify_waiters();
    }

    /// Fence admission (including in-flight `try_push` racers), then drop every
    /// undeliverable payload. Retained connection handles keep these Arcs alive,
    /// so without an explicit drain the bodies would outlive IO exit.
    fn close_and_reclaim(&self) {
        self.mark_closed_and_wake();
        loop {
            while self.queue.pop().is_some() {}
            let state = self.try_push_state.load(Ordering::Acquire);
            if state & STREAMING_QUEUE_PUSHERS == 0 {
                while self.queue.pop().is_some() {}
                break;
            }
            std::thread::yield_now();
        }
    }

    async fn push(&self, mut command: WriteCommand) -> Result<()> {
        loop {
            {
                // Admission guards cover only the synchronous publish attempt.
                // Holding one across `notified().await` lets teardown spin on
                // this thread while the waiter needs the same executor.
                let Some(_guard) = self.enqueue_guard() else {
                    return Err(GossipError::ConnectionClosed(self.addr));
                };
                match self.queue.push(command) {
                    Ok(()) => {
                        self.notify_data();
                        if self.closed.load(Ordering::Acquire) {
                            return Err(GossipError::ConnectionClosed(self.addr));
                        }
                        return Ok(());
                    }
                    Err(cmd) => command = cmd,
                }
            }
            // Register on the space notifier *before* re-checking
            // `closed`. `mark_closed_and_wake` signals via
            // `notify_waiters()`, which stores no permit for an
            // unregistered waiter, so a teardown landing between the
            // failed push and the await would otherwise be lost and
            // park this sender forever. `enable()` arms the waiter so
            // any close after this point is delivered to the await
            // below, and the close-before-enable case is caught by the
            // load that follows. Backpressure-branch only; never on the
            // `try_push` fast path.
            let notified = self.space_notify.notified();
            tokio::pin!(notified);
            notified.as_mut().enable();
            if self.closed.load(Ordering::Acquire) {
                return Err(GossipError::ConnectionClosed(self.addr));
            }
            notified.await;
            if self.closed.load(Ordering::Acquire) {
                return Err(GossipError::ConnectionClosed(self.addr));
            }
        }
    }

    fn pop(&self) -> Option<WriteCommand> {
        self.queue.pop()
    }

    fn notify_space(&self) {
        self.space_notify.notify_one();
    }
}

struct StreamEnqueueGuard<'a>(&'a StreamingQueue);

impl Drop for StreamEnqueueGuard<'_> {
    fn drop(&mut self) {
        self.0.try_push_state.fetch_sub(1, Ordering::AcqRel);
    }
}

struct StreamingQueue {
    queue: crossbeam_queue::ArrayQueue<StreamingCommand>,
    data_notify: Notify,
    space_notify: Notify,
    /// See `WriteQueue::data_pending`: producer wake coalescing flag, cleared
    /// by the consumer in `prepare_park()` immediately before parking.
    data_pending: AtomicBool,
    /// Set true when the owning IO writer task has exited (teardown). See
    /// `WriteQueue::closed`. Hot path never reads this flag.
    closed: AtomicBool,
    /// Coordinates non-blocking enqueues with teardown. The high bit is the
    /// closed flag; lower bits count enqueues that have started but not yet
    /// committed their result. An enqueue overlapping teardown must return
    /// `Closed`, even if it managed to append a command before the writer quit.
    try_push_state: AtomicUsize,
    /// Peer address used to construct the `ConnectionClosed` error on teardown.
    addr: SocketAddr,
    #[cfg(test)]
    space_notification_count: AtomicUsize,
}

const STREAMING_QUEUE_CLOSED: usize = 1usize << (usize::BITS - 1);
const STREAMING_QUEUE_PUSHERS: usize = !STREAMING_QUEUE_CLOSED;

#[derive(Debug)]
#[expect(
    dead_code,
    reason = "the error retains the rejected command for callers that need an explicit retry policy"
)]
enum StreamingTryPushError {
    Closed(SocketAddr),
    Full(StreamingCommand),
}

impl StreamingQueue {
    fn new(capacity: usize, addr: SocketAddr) -> Arc<Self> {
        Arc::new(Self {
            queue: crossbeam_queue::ArrayQueue::new(capacity.max(64)),
            data_notify: Notify::new(),
            space_notify: Notify::new(),
            data_pending: AtomicBool::new(false),
            closed: AtomicBool::new(false),
            try_push_state: AtomicUsize::new(0),
            addr,
            #[cfg(test)]
            space_notification_count: AtomicUsize::new(0),
        })
    }

    fn enqueue_guard(&self) -> Option<StreamEnqueueGuard<'_>> {
        loop {
            let state = self.try_push_state.load(Ordering::Acquire);
            if state & STREAMING_QUEUE_CLOSED != 0 {
                return None;
            }
            debug_assert!(state & STREAMING_QUEUE_PUSHERS != STREAMING_QUEUE_PUSHERS);
            if self
                .try_push_state
                .compare_exchange_weak(state, state + 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
            {
                return Some(StreamEnqueueGuard(self));
            }
        }
    }

    fn try_push(
        &self,
        command: StreamingCommand,
    ) -> std::result::Result<(), StreamingTryPushError> {
        let Some(_guard) = self.enqueue_guard() else {
            return Err(StreamingTryPushError::Closed(self.addr));
        };
        let result = match self.queue.push(command) {
            Ok(()) => {
                self.notify_data();
                Ok(())
            }
            Err(cmd) => Err(StreamingTryPushError::Full(cmd)),
        };
        if self.try_push_state.load(Ordering::Acquire) & STREAMING_QUEUE_CLOSED != 0 {
            return Err(StreamingTryPushError::Closed(self.addr));
        }
        result
    }

    /// See `WriteQueue::notify_data`: coalesced, permit-storing writer wakeup.
    #[inline]
    fn notify_data(&self) {
        #[cfg(test)]
        queue_notify_hook::fire(self.addr);
        if !self.data_pending.swap(true, Ordering::AcqRel) {
            self.data_notify.notify_one();
        }
    }

    /// See `WriteQueue::wake_consumer`: wake a writer parked on `data_notify`
    /// (consumer-only permit, never stolen by a producer) so it can re-check
    /// external state such as `shutdown_signal`.
    fn wake_consumer(&self) {
        self.data_notify.notify_one();
    }

    /// See `WriteQueue::prepare_park`: consumer-side pre-park drain.
    fn prepare_park(&self) -> Option<StreamingCommand> {
        self.data_pending.store(false, Ordering::Release);
        let command = self.pop();
        if command.is_some() {
            self.data_pending.store(true, Ordering::Release);
        }
        command
    }

    /// Mark the queue closed and wake every task parked in `push()`. Teardown-only.
    fn mark_closed_and_wake(&self) {
        self.try_push_state
            .fetch_or(STREAMING_QUEUE_CLOSED, Ordering::AcqRel);
        self.closed.store(true, Ordering::Release);
        self.space_notify.notify_waiters();
    }

    /// Fence admission (including in-flight `try_push` racers), then drop every
    /// undeliverable streaming payload. See `WriteQueue::close_and_reclaim`.
    fn close_and_reclaim(&self) {
        self.mark_closed_and_wake();
        loop {
            while self.queue.pop().is_some() {}
            let state = self.try_push_state.load(Ordering::Acquire);
            if state & STREAMING_QUEUE_PUSHERS == 0 {
                while self.queue.pop().is_some() {}
                break;
            }
            std::thread::yield_now();
        }
    }

    async fn push(&self, mut command: StreamingCommand) -> Result<()> {
        loop {
            {
                // See WriteQueue::push: do not hold the admission guard across
                // the backpressure wait, or teardown deadlocks this executor.
                let Some(_guard) = self.enqueue_guard() else {
                    return Err(GossipError::ConnectionClosed(self.addr));
                };
                match self.queue.push(command) {
                    Ok(()) => {
                        self.notify_data();
                        if self.closed.load(Ordering::Acquire) {
                            return Err(GossipError::ConnectionClosed(self.addr));
                        }
                        return Ok(());
                    }
                    Err(cmd) => command = cmd,
                }
            }
            // See WriteQueue::push: register before re-checking `closed`
            // so a teardown landing in the gap is not lost. Backpressure
            // branch only; never on the fast path.
            let notified = self.space_notify.notified();
            tokio::pin!(notified);
            notified.as_mut().enable();
            if self.closed.load(Ordering::Acquire) {
                return Err(GossipError::ConnectionClosed(self.addr));
            }
            notified.await;
            if self.closed.load(Ordering::Acquire) {
                return Err(GossipError::ConnectionClosed(self.addr));
            }
        }
    }

    fn pop(&self) -> Option<StreamingCommand> {
        self.queue.pop()
    }

    #[inline]
    fn has_pending(&self) -> bool {
        !self.queue.is_empty()
    }

    fn notify_space(&self) {
        #[cfg(test)]
        self.space_notification_count
            .fetch_add(1, Ordering::Relaxed);
        self.space_notify.notify_one();
    }

    #[cfg(test)]
    fn space_notification_count(&self) -> usize {
        self.space_notification_count.load(Ordering::Relaxed)
    }
}

/// Test/benchmark scaffolding for a raw (unaddressed) `Ask`
/// (`handle::handle_raw_ask_request`): recognizes a small set of ECHO:/
/// REVERSE:/COUNT:/HASH: commands and otherwise acknowledges the byte count
/// and raw content. A raw ask carries opaque bytes with no actor_id/
/// type_hash, so there is no production dispatcher to route it to -- this
/// exists purely so tests/benchmarks can exercise the raw-ask wire path
/// without standing up a registered actor. Production answers
/// `AskNackReason::NoDispatcher` instead; fabricating a transformed reply to
/// a real caller would be worse than the timeout it replaced.
#[cfg(any(test, feature = "test-helpers"))]
pub(crate) fn process_mock_request(request: &str) -> Vec<u8> {
    if let Some(payload) = request.strip_prefix("ECHO:") {
        return format!("ECHOED:{}", payload).into_bytes();
    }
    if let Some(payload) = request.strip_prefix("REVERSE:") {
        let reversed: String = payload.chars().rev().collect();
        return format!("REVERSED:{}", reversed).into_bytes();
    }
    if let Some(payload) = request.strip_prefix("COUNT:") {
        return format!("COUNTED:{} chars", payload.chars().count()).into_bytes();
    }
    if let Some(payload) = request.strip_prefix("HASH:") {
        let mut hasher = Sha256::new();
        hasher.update(payload.as_bytes());
        let digest = hasher.finalize();
        return format!("HASHED:{}", hex::encode(digest)).into_bytes();
    }

    format!("RECEIVED:{} bytes, content: '{}'", request.len(), request).into_bytes()
}

/// Byte-oriented entry point for `process_mock_request`: a 4-byte payload is
/// treated as a little protocol of its own (increment-and-echo, used by the
/// realistic correlation benchmark), anything else is treated as UTF-8 and
/// handed to `process_mock_request`.
#[cfg(any(test, feature = "test-helpers"))]
pub(crate) fn process_mock_request_payload(payload: &[u8]) -> Vec<u8> {
    if payload.len() == 4 {
        let value = u32::from_be_bytes([payload[0], payload[1], payload[2], payload[3]]);
        return (value + 1).to_be_bytes().to_vec();
    }

    let request_str = String::from_utf8_lossy(payload);
    process_mock_request(&request_str)
}

impl BufferConfig {
    /// Create a new BufferConfig with validation
    ///
    /// # Arguments
    /// * `tcp_buffer_size` - The size of TCP buffers in bytes
    ///
    /// # Errors
    /// Returns an error if the buffer size is less than 256KB for safety
    pub fn new(tcp_buffer_size: usize) -> Result<Self> {
        // Enforce minimum size of 256KB for safety
        if tcp_buffer_size < 256 * 1024 {
            return Err(GossipError::InvalidConfig(format!(
                "TCP buffer must be at least 256KB, got {}KB",
                tcp_buffer_size / 1024
            )));
        }
        Ok(Self {
            tcp_buffer_size,
            ask_window: crate::config::DEFAULT_ASK_WINDOW,
            write_queue_capacity: crate::config::DEFAULT_ASK_WINDOW.saturating_mul(8),
        })
    }

    /// Target in-flight ask window per connection.
    pub fn ask_window(&self) -> usize {
        self.ask_window
    }

    /// Override the default ask inflight limit.
    pub fn with_ask_window(mut self, limit: usize) -> Self {
        self.ask_window = limit;
        let min_capacity = limit.saturating_mul(4).max(128);
        if self.write_queue_capacity < min_capacity {
            self.write_queue_capacity = min_capacity;
        }
        self
    }

    /// Override write queue capacity (number of queued payloads before backpressure).
    pub fn with_write_queue_capacity(mut self, capacity: usize) -> Self {
        self.write_queue_capacity = capacity.max(128);
        self
    }

    /// Capacity of the write queue used by the lock-free writer task.
    pub fn write_queue_capacity(&self) -> usize {
        self.write_queue_capacity
    }

    /// Calculate the streaming threshold based on buffer size
    ///
    /// The streaming threshold is always derived from the buffer size,
    /// leaving 1KB headroom for headers and serialization overhead.
    pub fn streaming_threshold(&self) -> usize {
        // Always derive from buffer size
        // Leave 1KB headroom for headers/overhead
        self.tcp_buffer_size.saturating_sub(1024)
    }

    /// Get the TCP buffer size for BufWriter and io_uring
    ///
    /// This ensures TCP buffers match the configured size, preventing bottlenecks.
    pub fn tcp_buffer_size(&self) -> usize {
        self.tcp_buffer_size
    }

    /// Create BufferConfig using the master buffer size (recommended)
    pub fn from_master() -> Self {
        Self {
            tcp_buffer_size: MASTER_BUFFER_SIZE,
            ask_window: crate::config::DEFAULT_ASK_WINDOW,
            write_queue_capacity: crate::config::DEFAULT_ASK_WINDOW.saturating_mul(8),
        }
    }
}

impl Default for BufferConfig {
    fn default() -> Self {
        // Use master constant instead of magic number!
        Self {
            tcp_buffer_size: MASTER_BUFFER_SIZE,
            ask_window: crate::config::DEFAULT_ASK_WINDOW,
            write_queue_capacity: crate::config::DEFAULT_ASK_WINDOW.saturating_mul(8),
        }
    }
}

// Named `queue_notify_tests` (not `tests`) because `connection_pool` already
// declares a `tests` submodule and this file is `include!`d into `mod.rs`.
#[cfg(test)]
mod queue_notify_tests {
    use super::*;
    use std::future::Future;
    use std::sync::Barrier;
    use std::task::Waker;

    thread_local! {
        /// Marks the producer threads of the rendezvous tests so hook callers
        /// from unrelated tests in the same process never join the barrier.
        static HOOK_PARTY: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
    }

    fn test_addr() -> SocketAddr {
        "127.0.0.1:9".parse().expect("valid test addr")
    }

    /// Install a 2-party rendezvous in the push->notify window: both producer
    /// threads must reach the window before either proceeds to the notify
    /// decision.
    /// Caller must hold `queue_notify_hook::lock()` for the whole span from
    /// this call through the matching `queue_notify_hook::uninstall()`.
    fn install_two_party_rendezvous() {
        let barrier = Arc::new(Barrier::new(2));
        queue_notify_hook::install(
            test_addr(),
            Arc::new(move || {
                if HOOK_PARTY.with(|f| f.get()) {
                    barrier.wait();
                }
            }),
        );
    }

    /// Poll the queue's data notifier once with a no-op waker: a stored wakeup
    /// permit completes the future immediately, so `Ready` means a producer
    /// published a wakeup for the parked writer task.
    fn wakeup_published(notify: &Notify) -> bool {
        let notified = notify.notified();
        tokio::pin!(notified);
        let mut cx = Context::from_waker(Waker::noop());
        notified.as_mut().poll(&mut cx).is_ready()
    }

    fn frame() -> WriteCommand {
        WriteCommand::Payload(WritePayload::Single(bytes::Bytes::from_static(b"frame")))
    }

    fn immediate_frame() -> WriteCommand {
        WriteCommand::ImmediatePayload(WritePayload::Single(bytes::Bytes::from_static(
            b"immediate",
        )))
    }

    /// Immediate control replies have independent bounded admission and lead a
    /// regular writer turn. A saturated normal queue must therefore neither
    /// reject the reply nor place it behind the existing backlog.
    #[test]
    fn immediate_queue_reserves_admission_and_leads_saturated_normal_backlog() {
        let normal = WriteQueue::new(128, test_addr());
        let immediate = WriteQueue::new(128, test_addr());

        for _ in 0..128 {
            normal.try_push(frame()).expect("normal queue has capacity");
        }
        assert!(
            normal.try_push(frame()).is_err(),
            "normal queue is saturated"
        );

        immediate
            .try_push(immediate_frame())
            .expect("reserved immediate queue admits critical reply");

        let first = immediate
            .pop()
            .expect("writer drains priority queue before normal backlog");
        assert!(matches!(first, WriteCommand::ImmediatePayload(_)));
        assert_eq!(
            normal.queue.len(),
            128,
            "normal backlog was not consumed first"
        );
    }

    /// The priority lane is bounded per writer turn. After a control burst,
    /// normal traffic still receives its regular service budget.
    #[test]
    fn immediate_priority_budget_preserves_regular_queue_progress() {
        const IMMEDIATE_WRITE_BATCH: usize = 8;
        let normal = WriteQueue::new(128, test_addr());
        let immediate = WriteQueue::new(128, test_addr());
        normal.try_push(frame()).expect("normal queue has capacity");
        for _ in 0..(IMMEDIATE_WRITE_BATCH + 1) {
            immediate
                .try_push(immediate_frame())
                .expect("immediate queue has capacity");
        }

        let mut turn = Vec::new();
        for _ in 0..IMMEDIATE_WRITE_BATCH {
            turn.push(immediate.pop().expect("priority frame available"));
        }
        turn.push(normal.pop().expect("regular frame receives a fair turn"));

        assert!(
            turn[..IMMEDIATE_WRITE_BATCH]
                .iter()
                .all(|command| matches!(command, WriteCommand::ImmediatePayload(_)))
        );
        assert!(matches!(
            turn[IMMEDIATE_WRITE_BATCH],
            WriteCommand::Payload(_)
        ));
        assert_eq!(immediate.queue.len(), 1, "priority traffic remains bounded");
    }

    /// Two producers pushing concurrently into an EMPTY queue must publish a
    /// writer wakeup. With the `len() == 1` empty->non-empty heuristic, the
    /// interleaving pushA, pushB, lenA == 2, lenB == 2 notifies nobody and the
    /// writer stays parked with frames queued (lost wakeup).
    #[test]
    fn write_queue_concurrent_pushes_into_empty_queue_publish_wakeup() {
        let _guard = queue_notify_hook::lock();
        let queue = WriteQueue::new(128, test_addr());
        install_two_party_rendezvous();

        let producers: Vec<_> = (0..2)
            .map(|_| {
                let queue = queue.clone();
                std::thread::spawn(move || {
                    HOOK_PARTY.with(|f| f.set(true));
                    // Same call shape as LockFreeStreamHandle::enqueue_write_nonblocking.
                    queue.try_push(frame()).expect("queue has capacity");
                    queue.notify_data();
                })
            })
            .collect();
        for producer in producers {
            producer.join().expect("producer thread panicked");
        }
        queue_notify_hook::uninstall();

        assert_eq!(queue.queue.len(), 2, "both frames must be enqueued");
        assert!(
            wakeup_published(&queue.data_notify),
            "two producers pushed into an empty write queue but no wakeup was \
             published; the parked writer task would never drain the frames"
        );
    }

    /// Same lost-wakeup race for the streaming queue, driven through its
    /// public `try_push` path (which notifies internally).
    #[test]
    fn streaming_queue_concurrent_pushes_into_empty_queue_publish_wakeup() {
        let _guard = queue_notify_hook::lock();
        let queue = StreamingQueue::new(64, test_addr());
        install_two_party_rendezvous();

        let producers: Vec<_> = (0..2)
            .map(|_| {
                let queue = queue.clone();
                std::thread::spawn(move || {
                    HOOK_PARTY.with(|f| f.set(true));
                    queue
                        .try_push(StreamingCommand::Flush)
                        .expect("queue has capacity");
                })
            })
            .collect();
        for producer in producers {
            producer.join().expect("producer thread panicked");
        }
        queue_notify_hook::uninstall();

        assert_eq!(queue.queue.len(), 2, "both commands must be enqueued");
        assert!(
            wakeup_published(&queue.data_notify),
            "two producers pushed into an empty streaming queue but no wakeup \
             was published; the parked writer task would never drain the commands"
        );
    }

    /// Deterministic walk of the `prepare_park` clear window: a push whose
    /// wakeup was coalesced away (pending flag still set from an earlier
    /// burst) must be recovered by the pre-park re-check pop, and after the
    /// queue drains a fresh push must publish a wakeup again.
    #[test]
    fn streaming_queue_prepare_park_recovers_coalesced_push() {
        let queue = StreamingQueue::new(64, test_addr());

        // First push of a burst: flag transitions false -> true, permit stored.
        queue
            .try_push(StreamingCommand::Flush)
            .expect("queue has capacity");
        assert!(wakeup_published(&queue.data_notify), "first push must wake");

        // Second push while the flag is still set: coalesced, no new permit.
        queue
            .try_push(StreamingCommand::Flush)
            .expect("queue has capacity");
        assert!(
            !wakeup_published(&queue.data_notify),
            "coalesced push must not publish a second wakeup"
        );

        // Without prepare_park the writer would now park with frames queued.
        assert!(
            queue.prepare_park().is_some(),
            "pre-park drain must recover the coalesced frame"
        );
        assert!(queue.pop().is_some(), "second frame drains normally");
        assert!(queue.prepare_park().is_none(), "empty queue parks cleanly");

        // Flag was cleared by prepare_park: the next push must wake again.
        queue
            .try_push(StreamingCommand::Flush)
            .expect("queue has capacity");
        assert!(
            wakeup_published(&queue.data_notify),
            "push after a clean park must publish a wakeup"
        );
    }

    /// Stress the push / prepare_park race: a producer thread pushes frames
    /// while the consumer drains and parks exactly like the writer task. If a
    /// push racing the pending-flag clear window could lose its frame or its
    /// wakeup, the consumer would park forever and the timeout would fire.
    #[tokio::test]
    async fn write_queue_push_racing_prepare_park_never_loses_wakeup() {
        const FRAMES: usize = 20_000;
        let queue = WriteQueue::new(FRAMES, test_addr());

        let producer = {
            let queue = queue.clone();
            std::thread::spawn(move || {
                for _ in 0..FRAMES {
                    queue.try_push(frame()).expect("queue has capacity");
                    queue.notify_data();
                }
            })
        };

        let consumer = async {
            let mut received = 0usize;
            while received < FRAMES {
                // Drain as the writer loop's batch pop does.
                while queue.pop().is_some() {
                    received += 1;
                }
                if received >= FRAMES {
                    break;
                }
                // Park exactly like the writer: pre-park drain, then wait.
                if let Some(_command) = queue.prepare_park() {
                    received += 1;
                    continue;
                }
                queue.data_notify.notified().await;
            }
            received
        };

        let received = tokio::time::timeout(std::time::Duration::from_secs(10), consumer)
            .await
            .expect("consumer parked forever: wakeup lost while frames were queued");
        assert_eq!(received, FRAMES);
        producer.join().expect("producer thread panicked");
    }

    /// `AsyncWrite` that reports `Ok(0)` (WriteZero) on vectored writes, but
    /// caps re-issued writes: a correct caller surfaces WriteZero on the first
    /// `Ok(0)` and never re-issues, while a missing guard would spin forever —
    /// the cap turns that into a bounded, distinct error so the test fails
    /// cleanly instead of hanging the process at 100% CPU (R-7).
    struct WriteZeroVectored {
        calls: std::sync::atomic::AtomicUsize,
    }

    impl tokio::io::AsyncWrite for WriteZeroVectored {
        fn is_write_vectored(&self) -> bool {
            true
        }
        fn poll_write(
            self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
            _buf: &[u8],
        ) -> Poll<std::io::Result<usize>> {
            Poll::Ready(Ok(0))
        }
        fn poll_write_vectored(
            self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
            _bufs: &[std::io::IoSlice<'_>],
        ) -> Poll<std::io::Result<usize>> {
            let n = self.calls.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            if n >= 4096 {
                return Poll::Ready(Err(std::io::Error::other(
                    "vectored write re-issued 4096 times without progress (R-7 spin)",
                )));
            }
            Poll::Ready(Ok(0))
        }
        fn poll_flush(
            self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
        ) -> Poll<std::io::Result<()>> {
            Poll::Ready(Ok(()))
        }
        fn poll_shutdown(
            self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
        ) -> Poll<std::io::Result<()>> {
            Poll::Ready(Ok(()))
        }
    }

    /// A zero-byte vectored write must fail immediately on the live writer.
    #[tokio::test]
    async fn qa_r7_pending_response_ok0_errors_not_spins() {
        let mut stream = WriteZeroVectored {
            calls: std::sync::atomic::AtomicUsize::new(0),
        };
        let mut pending = PendingOrdinaryWrite::Chunks {
            chunks: vec![
                bytes::Bytes::copy_from_slice(
                    crate::framing::try_write_direct_response_header(1, 8)
                        .unwrap()
                        .as_slice(),
                ),
                bytes::Bytes::from_static(b"resp-one"),
                bytes::Bytes::copy_from_slice(
                    crate::framing::try_write_direct_response_header(2, 8)
                        .unwrap()
                        .as_slice(),
                ),
                bytes::Bytes::from_static(b"resp-two"),
            ],
            offset: 0,
        };
        assert!(matches!(
            poll_pending_ordinary_nowait(&mut stream, &mut pending).await,
            OrdinaryWriteProgress::Failed
        ));
        assert_eq!(stream.calls.load(std::sync::atomic::Ordering::SeqCst), 1);
        assert!(matches!(
            pending,
            PendingOrdinaryWrite::Chunks { offset: 0, .. }
        ));
    }
}

// R-I (P1): the response batch drain loops in `stream_writer.rs` accumulated
// frames up to a FRAME-COUNT cap only (`READ_BATCH_LIMIT` / 2048,
// `ASK_READ_BATCH_LIMIT` / 8192) with no byte-level bound, so a peer sending
// many max-size (~1 MiB) response payloads could force gigabytes of live
// `Bytes` into a single in-memory batch before anything flushed. These tests
// exercise the live ResponseBatch parking and resumable pending writer against
// a recording stream: push one frame, then let the byte-cap guard park it.
#[cfg(test)]
mod response_batch_byte_cap_tests {
    use super::*;

    /// Records every byte written via `write_vectored`/`write_all` in order,
    /// so tests can assert both total volume and exact frame ordering across
    /// however many flushes occur.
    #[derive(Default)]
    struct RecordingStream {
        written: Vec<u8>,
        write_vectored_calls: usize,
    }

    impl tokio::io::AsyncWrite for RecordingStream {
        fn poll_write(
            mut self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
            buf: &[u8],
        ) -> Poll<std::io::Result<usize>> {
            self.written.extend_from_slice(buf);
            Poll::Ready(Ok(buf.len()))
        }
        fn is_write_vectored(&self) -> bool {
            true
        }
        fn poll_write_vectored(
            mut self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
            bufs: &[std::io::IoSlice<'_>],
        ) -> Poll<std::io::Result<usize>> {
            self.write_vectored_calls += 1;
            let mut n = 0;
            for buf in bufs {
                self.written.extend_from_slice(buf);
                n += buf.len();
            }
            Poll::Ready(Ok(n))
        }
        fn poll_flush(
            self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
        ) -> Poll<std::io::Result<()>> {
            Poll::Ready(Ok(()))
        }
        fn poll_shutdown(
            self: std::pin::Pin<&mut Self>,
            _cx: &mut Context<'_>,
        ) -> Poll<std::io::Result<()>> {
            Poll::Ready(Ok(()))
        }
    }

    /// A payload just under `STREAMING_THRESHOLD`, matching the largest
    /// payload the batch paths (as opposed to the streaming path) ever carry.
    fn near_streaming_threshold_payload(fill: u8) -> bytes::Bytes {
        bytes::Bytes::from(vec![fill; STREAMING_THRESHOLD])
    }

    /// Drive the actual response parking/pending-write path at the byte cap.
    async fn drain_simulated_turn(frame_count: usize) -> (usize, Vec<u8>, usize) {
        let mut stream = RecordingStream::default();
        let mut batch = ResponseBatch::new(frame_count);
        let mut pending = None;
        let mut max_batch_bytes = 0usize;
        let mut committed = 0usize;
        for i in 0..frame_count {
            batch.push_bytes(i as u32, near_streaming_threshold_payload((i % 256) as u8));
            max_batch_bytes = max_batch_bytes.max(batch.total_bytes());
            park_ask_response_batch_if_over_byte_cap(&mut pending, &mut batch).unwrap();
            while let Some(write) = pending.as_mut() {
                match poll_pending_ordinary_nowait(&mut stream, write).await {
                    OrdinaryWriteProgress::Complete(n) => {
                        committed += n;
                        pending = None;
                    }
                    OrdinaryWriteProgress::Partial(n) => {
                        assert!(n > 0, "healthy recording stream must progress");
                        committed += n;
                    }
                    OrdinaryWriteProgress::Failed => panic!("recording write failed"),
                }
            }
        }
        park_ask_response_batch(&mut pending, &mut batch).unwrap();
        while let Some(write) = pending.as_mut() {
            match poll_pending_ordinary_nowait(&mut stream, write).await {
                OrdinaryWriteProgress::Complete(n) => {
                    committed += n;
                    pending = None;
                }
                OrdinaryWriteProgress::Partial(n) => {
                    assert!(n > 0);
                    committed += n;
                }
                OrdinaryWriteProgress::Failed => panic!("recording write failed"),
            }
        }
        assert!(batch.is_empty());
        assert_eq!(committed, stream.written.len());
        (stream.write_vectored_calls, stream.written, max_batch_bytes)
    }

    /// RED: with `STREAM_ACTIVE`-sized (~1 MiB) payloads, 32 frames is ~32 MiB
    /// — comfortably below both `READ_BATCH_LIMIT` (2048) and
    /// `ASK_READ_BATCH_LIMIT` (8192), so the old frame-count-only cap would
    /// never trigger and the whole 32 MiB would sit in one `ResponseBatch`
    /// until the single end-of-turn flush. This asserts the batch is never
    /// allowed to hold more than a small, fixed multiple of a single
    /// streaming-sized payload (`RESPONSE_BATCH_BYTE_CAP`) at once, proving a
    /// real byte-level cap is enforced independent of frame count.
    #[tokio::test]
    async fn response_batch_never_exceeds_byte_cap_regardless_of_frame_count() {
        const FRAMES: usize = 32;
        let (write_vectored_calls, written, max_batch_bytes) = drain_simulated_turn(FRAMES).await;

        assert!(
            max_batch_bytes <= RESPONSE_BATCH_BYTE_CAP,
            "batch accumulated {max_batch_bytes} bytes, exceeding the \
             RESPONSE_BATCH_BYTE_CAP of {RESPONSE_BATCH_BYTE_CAP} bytes; a \
             peer packing its ask window with max-size frames can force \
             unbounded per-turn memory growth"
        );

        // Bytes-capped batching must still have flushed more than once across
        // 32 MiB of payload (each write_vectored call carries at most the
        // byte cap's worth of frames), proving early flush actually fired
        // rather than accumulating everything into one end-of-turn write.
        assert!(
            write_vectored_calls > 1,
            "expected multiple early flushes once the byte cap was reached, \
             got only {write_vectored_calls} write_vectored call(s)"
        );

        // Frame ordering must be preserved across the early flushes: replay
        // the recorded bytes as a sequence of [header, payload] frames and
        // confirm correlation ids and payload fill bytes arrive 0..FRAMES in
        // order, with no frame dropped or duplicated.
        let mut offset = 0usize;
        for expected_id in 0..FRAMES {
            const HDR_LEN: usize = crate::framing::ASK_RESPONSE_FRAME_HEADER_LEN;
            const ASK_RESPONSE_HEADER_LEN: usize = crate::framing::ASK_RESPONSE_HEADER_LEN;
            assert!(
                offset + HDR_LEN <= written.len(),
                "missing frame header for correlation id {expected_id}"
            );
            let header = &written[offset..offset + HDR_LEN];
            let mut control_word = [0u8; crate::framing::LENGTH_PREFIX_LEN];
            control_word.copy_from_slice(&header[..crate::framing::LENGTH_PREFIX_LEN]);
            let control = crate::framing::decode_control(control_word)
                .expect("recorded bytes must contain a valid control word");
            assert_eq!(control.kind, crate::framing::WireKind::Response);
            let payload_len = control.body_len - ASK_RESPONSE_HEADER_LEN;
            let correlation_id = u32::from_be_bytes(header[4..8].try_into().unwrap());
            assert_eq!(
                correlation_id, expected_id as u32,
                "frame order was not preserved across an early byte-cap flush"
            );
            assert_eq!(payload_len, STREAMING_THRESHOLD);
            offset += HDR_LEN;

            let expected_fill = (expected_id % 256) as u8;
            let payload = &written[offset..offset + payload_len];
            assert!(
                payload.iter().all(|&b| b == expected_fill),
                "payload bytes for correlation id {expected_id} were corrupted \
                 or misaligned across an early byte-cap flush"
            );
            offset += payload_len;
        }
        assert_eq!(offset, written.len(), "no extra or missing trailing bytes");
    }
}
